kind: VirtualService
apiVersion: networking.istio.io/v1beta1
metadata:
  name: virtualservice
  namespace: default
spec:
  hosts:
    #- istio-ingressgateway-istio-system.apps.rco-ocp2.lab.rbbn.com
    - '*'
  gateways:
    - mygateway
  http:
    - match:
        - uri:
            prefix: /hello
      route:
        - destination:
            host: {{ include "aaclient.fullname" . }}
            port:
              number: 8080
status: {}

